### ISSUE TITLE
Dashboard improvements

### ISSUE THREAD

**Issue by barbeau** [barbeau/gpstest#595]
**Is your feature request related to a problem? Please describe.**
This issue is tracking improvements that can be made to the Dashboard feature that weren't finished in the initial implementation in PR https://github.com/barbeau/gpstest/pull/570.

**Describe the solution you'd like**
- [ ] GNSS/SBAS - More detailed stats for each constellation, including counts of satellites with almanac and ephemeris data and used, https://github.com/barbeau/gpstest/issues/365, https://github.com/barbeau/gpstest/issues/438
- [ ] dual-frequency - including number of dual-frequency satellites in view and used - https://github.com/barbeau/gpstest/issues/265
- [ ] GPSTest score - https://github.com/barbeau/gpstest/issues/313#issuecomment-874940602
- [ ] Disagreements between GnssStatus and raw meaurements APIs for CF - see https://github.com/barbeau/gpstest/issues/538
- [ ] SafetyNet pass/fail - or some other way to tell if you're running an official build. See https://developer.android.com/google/play/integrity/overview and https://developer.android.com/training/safetynet/attestation#overview
- [ ] NMEA DTM offsets
- [ ] Should time sync use https://developer.android.com/reference/android/os/SystemClock#currentGnssTimeClock() and https://developer.android.com/reference/android/os/SystemClock#currentNetworkTimeClock() instead?
- [ ] Power savings enabled or disabled
- [ ] Force full measurements enabled or disabled
- [ ] GNSS measurement interval
- [ ] Unit tests

**Comment by barbeau** [comment]
Not stale

**Comment by barbeau** [comment]
Not stale
